#配置免密，yum

---
- name:  configure authorized key
  hosts: all
  tasks:
  - name: root key                    #免密登陆
    authorized_key:
      user: root
      state:  present
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  - name: copy yum config file         #配置yum

    copy:
      src:  files/192.168.4.254_rhel7.repo    #本机目录
      dest: /etc/yum.repos.d/                 #要远程配置的目录


#执行playbook
#•  检查语法
#[root@bogon	myansi]#	ansible-playbook	--syntax-check	auth_key.yml
#•  执行
#[root@bogon	myansi]#	ansible-playbook	auth_key.yml	-k(交互密码)
